version: 1.0.{build}
image: WMF 5
install:
- ps: >-
    Install-PackageProvider -Name NuGet –Force

    Install-Package -Name Pester -ProviderName PowerShellGet -Scope AllUsers -Force

    Install-Module -Name PSScriptAnalyzer -Scope AllUsers –Force

    Import-Module -Name Pester

    Import-Module -Name PSScriptAnalyzer

    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\${Env:APPVEYOR_PROJECT_NAME}.zip" "${Env:APPVEYOR_BUILD_FOLDER}"

    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\deploy.zip" "deploy.ps1"
build: off
test_script:
- ps: >-
    $testResultsFile = ".\TestsResults.xml"

    $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($Env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))

    If ($results.FailedCount -gt 0) {
      throw "$($results.FailedCount) tests failed."
    }
artifacts:
- path: '*.zip'
  name: VMWFS14
deploy:
- provider: Environment
  name: VMWFS14
  on:
    branch: master
